# Generated by Django 5.1.4 on 2025-01-21 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_contact', models.CharField(max_length=80)),
                ('date_contact', models.CharField(max_length=10)),
                ('number_act', models.IntegerField(max_length=5)),
                ('project', models.CharField(max_length=150)),
                ('stavka', models.FloatField(max_length=10)),
                ('date_start', models.CharField(max_length=10)),
                ('date_end', models.CharField(max_length=10)),
                ('time_of_work', models.FloatField(max_length=15)),
                ('name_of_work', models.CharField(max_length=80)),
                ('result_of_work', models.CharField(max_length=80)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('total', models.FloatField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.customuser')),
            ],
        ),
    ]
