# Generated by Django 5.1.4 on 2025-01-21 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mymodel_number_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.customuser'),
        ),
    ]
