# Generated by Django 5.1.4 on 2025-01-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_mymodel_created_at_alter_mymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date_end',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='date_start',
            field=models.DateField(max_length=10),
        ),
    ]
