# Generated by Django 5.1.4 on 2025-01-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_mymodel_date_end_alter_mymodel_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date_end',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='date_start',
            field=models.CharField(max_length=10),
        ),
    ]
