# Generated by Django 5.1.4 on 2025-01-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mymodel_date_end_alter_mymodel_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='stavka',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
