# Generated by Django 5.1.4 on 2025-01-24 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_mymodel_stavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='stavka',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
