# Generated by Django 5.1.4 on 2025-01-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_mymodel_stavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='stavka',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
