# Generated by Django 5.1.4 on 2025-01-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_mymodel_stavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='stavka',
            field=models.CharField(default=0.0, max_length=10),
        ),
    ]
