# Generated by Django 5.1.4 on 2025-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_mymodel_stavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='stavka',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='time_of_work',
            field=models.FloatField(),
        ),
    ]
