# Generated by Django 5.1.4 on 2025-01-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_mymodel_stavka_alter_mymodel_time_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_of_worker',
            field=models.CharField(choices=[('Self-employed', 'Самозанятый'), ('IP', 'Индивидуальный предприниматель')], max_length=100),
        ),
    ]
