# Generated by Django 5.1.4 on 2025-01-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_customuser_type_of_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_of_worker',
            field=models.CharField(choices=[('Самозанятый', 'Самозанятый'), ('Индивидуальный предприниматель', 'Индивидуальный предприниматель')], max_length=100),
        ),
    ]
