# Generated by Django 5.1.4 on 2025-02-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_mymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='text_error',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
